all:
	gcc -o libsilica_test libsilica_test.c libsilica.c libsilica_dsp_types.h fpga/xilinx/dma/libsilica_fpga_xilinx_dma.c		

fpga_xilinx_dma_test:
	gcc -o libsilica_fpga_xilinx_dma_test fpga/xilinx/dma/libsilica_fpga_xilinx_dma_test.c libsilica.c libsilica_dsp_types.h fpga/xilinx/dma/libsilica_fpga_xilinx_dma.c		
