#ifndef PARAMS_MODULES_FILTER_BANDPASS_H
#define PARAMS_MODULES_FILTER_BANDPASS_H

/* user-exposed parameters */
#define PARAM_USER_HOSTNAME_IP 0
#define PARAM_USER_OSC_PATH 1
#define PARAM_USER_PORT 0
#define PARAM_USER_FREQ_DIV 0

/* internal module parameters */
#define PARAM_INTERNAL_SAMPLERATE_COUNTER 1
#define PARAM_INTERNAL_LO_ADDR_SEND 0
#define PARAM_INTERNAL_LO_ADDR_SEND_STAGED 1
#define PARAM_INTERNAL_LO_ADDR_SEND_EXPIRED 2
#define PARAM_INTERNAL_LO_ADDR_SEND_STAGED_STATE 0
#define PARAM_INTERNAL_LO_ADDR_SEND_GARBAGE_STATE 1

#endif
