#ifndef PARAMS_MODULES_ENVELOPE_FOLLOWER_H
#define PARAMS_MODULES_ENVELOPE_FOLLOWER_H

/* user-exposed parameters */
#define PARAM_USER_ATTACK_MS 0
#define PARAM_USER_DECAY_MS 1
#define PARAM_USER_SCALE 2

/* internal module parameters */
#define PARAM_INTERNAL_LAST_OUTPUT 0
#define PARAM_INTERNAL_ATTACK_MS 3
#define PARAM_INTERNAL_DECAY_MS 4
#define PARAM_INTERNAL_COEFF_ATTACK 5
#define PARAM_INTERNAL_COEFF_DECAY 6
#define PARAM_INTERNAL_ATTACK_MS_CONNECTED 0
#define PARAM_INTERNAL_DECAY_MS_CONNECTED 1

/* listener-exposed parameters */
#define PARAM_LISTENER_ATTACK_MS 1
#define PARAM_LISTENER_DECAY_MS 2
#define PARAM_LISTENER_SCALE 3

#endif
